/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cliente_Prototipo01.java
 *
 * Created on 09-jul-2011, 23:19:20
 */
package cl.eh.client;


import cl.eh.common.PunteroArduino;
import cl.eh.common.Network;
import cl.eh.common.Network.ArduinoInput;
import cl.eh.common.Network.HistorialList;
import cl.eh.common.Network.ValidacionConnection;
import cl.eh.properties.PropiedadesClient;
import java.io.IOException;
import com.esotericsoftware.kryonet.Client;
import com.esotericsoftware.kryonet.Connection;
import com.esotericsoftware.kryonet.Listener;
import com.esotericsoftware.minlog.Log;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Cliente_Prototipo01 extends javax.swing.JFrame {

    private PropiedadesClient p;
    private Client client;

    /** Creates new form Cliente_Prototipo01 */
    public Cliente_Prototipo01() {
        initComponents();
        misComponentes();
        cargarCliente();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        b_rl01 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_estado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Programacion de eventos", jPanel1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("RL01");

        b_rl01.setText("Accionar");
        b_rl01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_rl01ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Estado:");

        lbl_estado.setFont(new java.awt.Font("Tahoma", 1, 14));
        lbl_estado.setText("unknow");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_rl01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_estado)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(b_rl01)
                    .addComponent(jLabel2)
                    .addComponent(lbl_estado))
                .addContainerGap(286, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Actuadores", jPanel2);

        jButton1.setText("EnviarObjectoAServidor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Test", jPanel3);

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Conectar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Desconectar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //BOTON CONECTAR
        new Thread("Connect") {

            @Override
            public void run() {
                try {
                    client.connect(5000, p.getIp(), Network.getNetworkPort());
                    jTabbedPane1.setEnabled(true);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Servidor no Disponible");
                }
            }
        }.start();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        client.close();
        jTabbedPane1.setEnabled(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(1);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void b_rl01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_rl01ActionPerformed
        ArduinoInput ai = new ArduinoInput();
        ai.señal = PunteroArduino.RL01;
        client.sendTCP(ai);
    }//GEN-LAST:event_b_rl01ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        HistorialList his = new HistorialList();
        his.lista = new ArrayList<String>();
        int sendTCP = client.sendTCP(his);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Cliente_Prototipo01().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_rl01;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_estado;
    // End of variables declaration//GEN-END:variables

    private void misComponentes() {
        p = new PropiedadesClient();
        p.getAllClientPropiedadesOfFile();
    }

    private void cargarCliente() {
        Log.set(Log.LEVEL_DEBUG);
        client = new Client();
        client.start();
        Network.register(client);
        client.addListener(new Listener() {
            @Override
            public void connected(Connection connection) {
                ValidacionConnection vc = new ValidacionConnection();
                vc.user = Network.LOCALUSER;
                client.sendTCP(vc);
            }

            @Override
            public void disconnected(Connection connection) {
                System.out.println("El servidor se ha caido:");
            }

            @Override
            public void received(Connection connection, Object object) {
                if(object instanceof Network.InvalidConnection){
                    JOptionPane.showMessageDialog(rootPane,
                            "Coneccion rechasada.. usuario invalido");
                    return;
                }
                if (object instanceof String) {
                    String asd = (String) object;
                    if (asd.charAt(0) == '7') {//el 7 es de los print de arduino
                        final String rec = asd.substring(1);

                        /*SwingUtilities.invokeLater(new Runnable() {
                        public void run() {
                        /*HACER ALGO
                        }
                        });*/
                        try {
                            String t_v[] = rec.split("\\|");//nombre y valor
                            t_v[1] = t_v[1].replace(";", "");
                            System.out.println(t_v[1]);
                            if (t_v[0].equalsIgnoreCase("RL01")) {

                                if (Integer.parseInt(t_v[1]) == 0) {//significa que esta pagado
                                    lbl_estado.setText("Apagado");
                                } else {
                                    lbl_estado.setText("Encendido");
                                }

                            }
                        } catch (Exception pene) {
                            System.out.println(pene.getMessage());
                        }
                    }

                }
            }
        });
    }
}
