/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExtendedHouseClient.java
 *
 * Created on 04-sep-2011, 1:00:20
 */
package cl.eh.client;

import cl.eh.client.status.StatusExtendedHouse;
import cl.eh.common.ArduinoSignal;
import cl.eh.common.ClientArduinoSignal;
import cl.eh.common.Network;
import cl.eh.common.Network.*;
import com.esotericsoftware.kryonet.Client;
import com.esotericsoftware.kryonet.Connection;
import com.esotericsoftware.kryonet.Listener;
import com.esotericsoftware.minlog.Log;
import java.io.IOException;
import java.security.AccessController;
import java.security.PrivilegedAction;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ExtendedHouseClient extends javax.swing.JApplet {
    private final boolean pruebaLocal = false;
    private Client client;
    private StatusExtendedHouse status_eh;
    private Parametros params;
    
    /** Initializes the applet ExtendedHouseClient */
    
    @Override
    public void init() {
        status_eh = new StatusExtendedHouse();
        params = new Parametros(
                super.getParameter(Parametros.PARAM_SERVERIP),
                super.getParameter(Parametros.PARAM_CLIENTIP),
                super.getParameter(Parametros.PARAM_USER));
        
        
        loadCliente();
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        
        jLabel3.setText("ip_cliente"+params.getIp_cliente());
        jLabel28.setText("ipserver:"+params.getIp_server());
        jLabel29.setText("user:"+params.getUser());
    
    }
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btn_rele7_off = new javax.swing.JButton();
        btn_rele7_on = new javax.swing.JButton();
        btn_rele1_on = new javax.swing.JButton();
        btn_rele2_on = new javax.swing.JButton();
        btn_rele3_on = new javax.swing.JButton();
        btn_rele4_on = new javax.swing.JButton();
        btn_rele5_on = new javax.swing.JButton();
        btn_rele6_on = new javax.swing.JButton();
        btn_rele1_off = new javax.swing.JButton();
        btn_rele2_off = new javax.swing.JButton();
        btn_rele3_off = new javax.swing.JButton();
        btn_rele4_off = new javax.swing.JButton();
        btn_rele5_off = new javax.swing.JButton();
        btn_rele6_off = new javax.swing.JButton();
        btn_rele8_off = new javax.swing.JButton();
        btn_rele8_on = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txt_usuarios = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 47, -1));

        jTextField3.setEditable(false);
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 290, -1));

        jButton1.setText("Conectar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 10, 370, -1));

        jLabel1.setText("status");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sensores"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Sensor Luz:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel5.setText("            ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel6.setText("Temperatura:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel7.setText("            ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel8.setText("Magnetico 4:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel9.setText("            ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jLabel10.setText("Magnetico 1:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel11.setText("Magnetico 2:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel12.setText("Magnetico 3:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel13.setText("            ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel14.setText("            ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel15.setText("            ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jLabel16.setText("Sensor Mov:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel17.setText("            ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 200, 190));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Actuadores"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("Rele 7:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel19.setText("Rele 1:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel20.setText("Rele 2:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel21.setText("Rele 3:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel22.setText("Rele 4:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel23.setText("Rele 5:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel24.setText("Rele 6:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        btn_rele7_off.setText("Off");
        btn_rele7_off.setEnabled(false);
        btn_rele7_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rele7_offActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rele7_off, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 20));

        btn_rele7_on.setText("On");
        btn_rele7_on.setEnabled(false);
        btn_rele7_on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rele7_onActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rele7_on, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 20));

        btn_rele1_on.setText("On");
        btn_rele1_on.setEnabled(false);
        btn_rele1_on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rele1_onActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rele1_on, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 20));

        btn_rele2_on.setText("On");
        btn_rele2_on.setEnabled(false);
        btn_rele2_on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rele2_onActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rele2_on, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, 20));

        btn_rele3_on.setText("On");
        btn_rele3_on.setEnabled(false);
        btn_rele3_on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rele3_onActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rele3_on, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 20));

        btn_rele4_on.setText("On");
        btn_rele4_on.setEnabled(false);
        btn_rele4_on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rele4_onActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rele4_on, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 20));

        btn_rele5_on.setText("On");
        btn_rele5_on.setEnabled(false);
        btn_rele5_on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rele5_onActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rele5_on, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        btn_rele6_on.setText("On");
        btn_rele6_on.setEnabled(false);
        btn_rele6_on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rele6_onActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rele6_on, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 20));

        btn_rele1_off.setText("Off");
        btn_rele1_off.setEnabled(false);
        btn_rele1_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rele1_offActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rele1_off, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 20));

        btn_rele2_off.setText("Off");
        btn_rele2_off.setEnabled(false);
        btn_rele2_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rele2_offActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rele2_off, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 20));

        btn_rele3_off.setText("Off");
        btn_rele3_off.setEnabled(false);
        btn_rele3_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rele3_offActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rele3_off, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 20));

        btn_rele4_off.setText("Off");
        btn_rele4_off.setEnabled(false);
        btn_rele4_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rele4_offActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rele4_off, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, 20));

        btn_rele5_off.setText("Off");
        btn_rele5_off.setEnabled(false);
        btn_rele5_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rele5_offActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rele5_off, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 20));

        btn_rele6_off.setText("Off");
        btn_rele6_off.setEnabled(false);
        btn_rele6_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rele6_offActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rele6_off, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, 20));

        btn_rele8_off.setText("Off");
        btn_rele8_off.setEnabled(false);
        btn_rele8_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rele8_offActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rele8_off, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, 20));

        btn_rele8_on.setText("On");
        btn_rele8_on.setEnabled(false);
        btn_rele8_on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rele8_onActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rele8_on, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 20));

        jLabel25.setText("Rele 8:");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 160, 280));

        jLabel26.setText("Server Info:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel27.setText("Usuarios Conectados:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        txt_usuarios.setEditable(false);
        getContentPane().add(txt_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 60, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Developer Info:"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel28.setText("jLabel28");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel29.setText("jLabel29");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new Thread("Conectar a servidor") {

            @Override
            public void run() {
                try {
                    if(pruebaLocal){
                        client.connect(5000, "127.0.0.1", Network.getNetworkPort());
                    }else{
                        client.connect(5000, params.getIp_server(), Network.getNetworkPort());
                    }
                    
                    jTextField2.setText("UP");
                    jTextField2.setForeground(new java.awt.Color(0, 255, 0));
                    /*VALIDO ALTOKE ^^*/
                } catch (IOException ex) {
                    jTextField2.setText("DOWN");
                    jTextField2.setForeground(new java.awt.Color(255, 0, 0));
                }
            }
        }.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_rele1_onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rele1_onActionPerformed
        int señal = 0 ; int valor = 1;
        ArduinoInput ai = new ArduinoInput();
        ai.dispositivo = señal;
        ai.señal = ArduinoSignal.RELEE_SIGNAL;
        ai.valor = valor;
        client.sendTCP(ai);
    }//GEN-LAST:event_btn_rele1_onActionPerformed

    private void btn_rele1_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rele1_offActionPerformed
        int señal = 0 ; int valor = 0;
        ArduinoInput ai = new ArduinoInput();
        ai.dispositivo = señal;
        ai.señal = ArduinoSignal.RELEE_SIGNAL;
        ai.valor = valor;
        client.sendTCP(ai);
    }//GEN-LAST:event_btn_rele1_offActionPerformed

    private void btn_rele2_onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rele2_onActionPerformed
        int señal = 1 ; int valor = 1;
        ArduinoInput ai = new ArduinoInput();
        ai.dispositivo = señal;
        ai.señal = ArduinoSignal.RELEE_SIGNAL;
        ai.valor = valor;
        client.sendTCP(ai);
    }//GEN-LAST:event_btn_rele2_onActionPerformed

    private void btn_rele2_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rele2_offActionPerformed
        int señal = 1 ; int valor = 0;
        ArduinoInput ai = new ArduinoInput();
        ai.dispositivo = señal;
        ai.señal = ArduinoSignal.RELEE_SIGNAL;
        ai.valor = valor;
        client.sendTCP(ai);
    }//GEN-LAST:event_btn_rele2_offActionPerformed

    private void btn_rele3_onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rele3_onActionPerformed
        int señal = 2 ; int valor = 1;
        ArduinoInput ai = new ArduinoInput();
        ai.dispositivo = señal;
        ai.señal = ArduinoSignal.RELEE_SIGNAL;
        ai.valor = valor;
        client.sendTCP(ai);
    }//GEN-LAST:event_btn_rele3_onActionPerformed

    private void btn_rele3_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rele3_offActionPerformed
        int señal = 2 ; int valor = 0;
        ArduinoInput ai = new ArduinoInput();
        ai.dispositivo = señal;
        ai.señal = ArduinoSignal.RELEE_SIGNAL;
        ai.valor = valor;
        client.sendTCP(ai);
    }//GEN-LAST:event_btn_rele3_offActionPerformed

    private void btn_rele4_onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rele4_onActionPerformed
        int señal = 3 ; int valor = 1;
        ArduinoInput ai = new ArduinoInput();
        ai.dispositivo = señal;
        ai.señal = ArduinoSignal.RELEE_SIGNAL;
        ai.valor = valor;
        client.sendTCP(ai);
    }//GEN-LAST:event_btn_rele4_onActionPerformed

    private void btn_rele4_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rele4_offActionPerformed
        int señal = 3 ; int valor = 0;
        ArduinoInput ai = new ArduinoInput();
        ai.dispositivo = señal;
        ai.señal = ArduinoSignal.RELEE_SIGNAL;
        ai.valor = valor;
        client.sendTCP(ai);
    }//GEN-LAST:event_btn_rele4_offActionPerformed

    private void btn_rele5_onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rele5_onActionPerformed
        int señal = 4 ; int valor = 1;
        ArduinoInput ai = new ArduinoInput();
        ai.dispositivo = señal;
        ai.señal = ArduinoSignal.RELEE_SIGNAL;
        ai.valor = valor;
        client.sendTCP(ai);
    }//GEN-LAST:event_btn_rele5_onActionPerformed

    private void btn_rele5_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rele5_offActionPerformed
        int señal = 4 ; int valor = 0;
        ArduinoInput ai = new ArduinoInput();
        ai.dispositivo = señal;
        ai.señal = ArduinoSignal.RELEE_SIGNAL;
        ai.valor = valor;
        client.sendTCP(ai);
    }//GEN-LAST:event_btn_rele5_offActionPerformed

    private void btn_rele6_onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rele6_onActionPerformed
        int señal = 5 ; int valor = 1;
        ArduinoInput ai = new ArduinoInput();
        ai.dispositivo = señal;
        ai.señal = ArduinoSignal.RELEE_SIGNAL;
        ai.valor = valor;
        client.sendTCP(ai);
    }//GEN-LAST:event_btn_rele6_onActionPerformed

    private void btn_rele6_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rele6_offActionPerformed
        int señal = 5 ; int valor = 0;
        ArduinoInput ai = new ArduinoInput();
        ai.dispositivo = señal;
        ai.señal = ArduinoSignal.RELEE_SIGNAL;
        ai.valor = valor;
        client.sendTCP(ai);
    }//GEN-LAST:event_btn_rele6_offActionPerformed

    private void btn_rele7_onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rele7_onActionPerformed
        int señal = 6 ; int valor = 1;
        ArduinoInput ai = new ArduinoInput();
        ai.dispositivo = señal;
        ai.señal = ArduinoSignal.RELEE_SIGNAL;
        ai.valor = valor;
        client.sendTCP(ai);
    }//GEN-LAST:event_btn_rele7_onActionPerformed

    private void btn_rele7_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rele7_offActionPerformed
        int señal = 6 ; int valor = 0;
        ArduinoInput ai = new ArduinoInput();
        ai.dispositivo = señal;
        ai.señal = ArduinoSignal.RELEE_SIGNAL;
        ai.valor = valor;
        client.sendTCP(ai);
    }//GEN-LAST:event_btn_rele7_offActionPerformed

    private void btn_rele8_onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rele8_onActionPerformed
        int señal = 7 ; int valor = 1;
        ArduinoInput ai = new ArduinoInput();
        ai.dispositivo = señal;
        ai.señal = ArduinoSignal.RELEE_SIGNAL;
        ai.valor = valor;
        client.sendTCP(ai);
    }//GEN-LAST:event_btn_rele8_onActionPerformed

    private void btn_rele8_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rele8_offActionPerformed
        int señal = 7 ; int valor = 0;
        ArduinoInput ai = new ArduinoInput();
        ai.dispositivo = señal;
        ai.señal = ArduinoSignal.RELEE_SIGNAL;
        ai.valor = valor;
        client.sendTCP(ai);
    }//GEN-LAST:event_btn_rele8_offActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_rele1_off;
    private javax.swing.JButton btn_rele1_on;
    private javax.swing.JButton btn_rele2_off;
    private javax.swing.JButton btn_rele2_on;
    private javax.swing.JButton btn_rele3_off;
    private javax.swing.JButton btn_rele3_on;
    private javax.swing.JButton btn_rele4_off;
    private javax.swing.JButton btn_rele4_on;
    private javax.swing.JButton btn_rele5_off;
    private javax.swing.JButton btn_rele5_on;
    private javax.swing.JButton btn_rele6_off;
    private javax.swing.JButton btn_rele6_on;
    private javax.swing.JButton btn_rele7_off;
    private javax.swing.JButton btn_rele7_on;
    private javax.swing.JButton btn_rele8_off;
    private javax.swing.JButton btn_rele8_on;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txt_usuarios;
    // End of variables declaration//GEN-END:variables

    private void setButtonEnable(JButton boton,boolean estado){
        boton.setEnabled(estado);
    }
    /*
    private void setsButtonsRelayState() {
        if (status_eh.getValorActuadorRelay(0) == 0) {
            setButtonEnable(btn_rele1_off, false);
            setButtonEnable(btn_rele1_on, true);
        } else {
            setButtonEnable(btn_rele1_off, true);
            setButtonEnable(btn_rele1_on, false);
        }
        if (status_eh.getValorActuadorRelay(1) == 0) {
            setButtonEnable(btn_rele2_off, false);
            setButtonEnable(btn_rele2_on, true);
        } else {
            setButtonEnable(btn_rele2_off, true);
            setButtonEnable(btn_rele2_on, false);
        }
        if (status_eh.getValorActuadorRelay(2) == 0) {
            setButtonEnable(btn_rele3_off, false);
            setButtonEnable(btn_rele3_on, true);
        } else {
            setButtonEnable(btn_rele3_off, true);
            setButtonEnable(btn_rele3_on, false);
        }
        if (status_eh.getValorActuadorRelay(3) == 0) {
            setButtonEnable(btn_rele4_off, false);
            setButtonEnable(btn_rele4_on, true);
        } else {
            setButtonEnable(btn_rele4_off, true);
            setButtonEnable(btn_rele4_on, false);
        }
        if (status_eh.getValorActuadorRelay(4) == 0) {
            setButtonEnable(btn_rele5_off, false);
            setButtonEnable(btn_rele5_on, true);
        } else {
            setButtonEnable(btn_rele5_off, true);
            setButtonEnable(btn_rele5_on, false);
        }
        if (status_eh.getValorActuadorRelay(5) == 0) {
            setButtonEnable(btn_rele6_off, false);
            setButtonEnable(btn_rele6_on, true);
        } else {
            setButtonEnable(btn_rele6_off, true);
            setButtonEnable(btn_rele6_on, false);
        }
        if (status_eh.getValorActuadorRelay(6) == 0) {
            setButtonEnable(btn_rele7_off, false);
            setButtonEnable(btn_rele7_on, true);
        } else {
            setButtonEnable(btn_rele7_off, true);
            setButtonEnable(btn_rele7_on, false);
        }
        if (status_eh.getValorActuadorRelay(7) == 0) {
            setButtonEnable(btn_rele8_off, false);
            setButtonEnable(btn_rele8_on, true);
        } else {
            setButtonEnable(btn_rele8_off, true);
            setButtonEnable(btn_rele8_on, false);
        }
        for(int i = 0; i < 8; i++){
            System.out.println(i+"|||"+status_eh.getValorActuadorRelay(i));
        }

    }*/

    private void loadCliente() {
        Log.set(Log.LEVEL_DEBUG);
        client = new Client();
        client.start();
        Network.register(client);
        client.addListener(new Listener() {
            @Override
            public void connected(Connection connection) {
                ValidacionConnection vc = new ValidacionConnection();
                if(!pruebaLocal){
                    vc.user = params.getUser();
                    vc.client_ip = params.getIp_cliente();
                }else{
                    vc.user = "extended_house";
                    vc.client_ip = "127.0.0.1";
                }
                
                client.sendTCP(vc); //validacion de connecion
                client.sendTCP(new ServerStatusRequest()); //peticion del estado del servidor
                
            }

            @Override
            public void disconnected(Connection connection) {
                System.out.println("El servidor se ha caido:");
                jTextField2.setText("DOWN");
                jTextField2.setForeground(new java.awt.Color(255, 0, 0));
            }

            @Override
            public void received(Connection connection, Object object) {
                if(object instanceof Network.InvalidConnection){
                    JOptionPane.showMessageDialog(rootPane,
                            "Coneccion rechasada.. usuario invalido");
                    return;
                }else if(object instanceof ArduinoOutput){
                    ArduinoOutput ao = (ArduinoOutput)object;
                    String dispostv = ao.dispositivo;
                    int numero = Integer.parseInt(ao.numero);
                    int valor  = (int)ao.valor;
                    
                    if(dispostv.equals(ClientArduinoSignal.TEMPERATURA_SIGNAL)){
                        status_eh.updateSensorTemperatura(numero,valor);
                        
                        jLabel7.setText(Integer.toString(status_eh.getValorSensorTemperatura(
                                Integer.parseInt(ao.numero))));
                    
                    }else if(dispostv.equals(ClientArduinoSignal.LUZ_SIGNAL)){
                        status_eh.updateSensorLuminico(numero,valor);
                        
                        jLabel5.setText(Integer.toString(status_eh.getValorSensorLuminico(
                                Integer.parseInt(ao.numero))));
                    
                    } else if (dispostv.equals(ClientArduinoSignal.RELEE_SIGNAL)) {
                        status_eh.updateActuadorRelay(numero, valor);
                        switch (numero) {
                            case 0: {
                                if (valor == 0) {
                                    setButtonEnable(btn_rele1_off, false);
                                    setButtonEnable(btn_rele1_on, true);
                                } else {
                                    setButtonEnable(btn_rele1_off, true);
                                    setButtonEnable(btn_rele1_on, false);
                                }
                                break;
                            }
                            case 1: {
                                if (valor == 0) {
                                    setButtonEnable(btn_rele2_off, false);
                                    setButtonEnable(btn_rele2_on, true);
                                } else {
                                    setButtonEnable(btn_rele2_off, true);
                                    setButtonEnable(btn_rele2_on, false);
                                }
                                break;
                            }
                            case 2: {
                                if (valor == 0) {
                                    setButtonEnable(btn_rele3_off, false);
                                    setButtonEnable(btn_rele3_on, true);
                                } else {
                                    setButtonEnable(btn_rele3_off, true);
                                    setButtonEnable(btn_rele3_on, false);
                                }
                                break;
                            }
                            case 3: {
                                if (valor == 0) {
                                    setButtonEnable(btn_rele4_off, false);
                                    setButtonEnable(btn_rele4_on, true);
                                } else {
                                    setButtonEnable(btn_rele4_off, true);
                                    setButtonEnable(btn_rele4_on, false);
                                }
                                break;
                            }
                            case 4: {
                                if (valor == 0) {
                                    setButtonEnable(btn_rele5_off, false);
                                    setButtonEnable(btn_rele5_on, true);
                                } else {
                                    setButtonEnable(btn_rele5_off, true);
                                    setButtonEnable(btn_rele5_on, false);
                                }
                                break;
                            }
                            case 5: {
                                if (valor == 0) {
                                    setButtonEnable(btn_rele6_off, false);
                                    setButtonEnable(btn_rele6_on, true);
                                } else {
                                    setButtonEnable(btn_rele6_off, true);
                                    setButtonEnable(btn_rele6_on, false);
                                }
                                break;
                            }
                            case 6: {
                                if (valor == 0) {
                                    setButtonEnable(btn_rele7_off, false);
                                    setButtonEnable(btn_rele7_on, true);
                                } else {
                                    setButtonEnable(btn_rele7_off, true);
                                    setButtonEnable(btn_rele7_on, false);
                                }
                                break;
                            }
                            case 7: {
                                if (valor == 0) {
                                    setButtonEnable(btn_rele8_off, false);
                                    setButtonEnable(btn_rele8_on, true);
                                } else {
                                    setButtonEnable(btn_rele8_off, true);
                                    setButtonEnable(btn_rele8_on, false);
                                }
                                break;
                            }
                        }
                    
                    }else if(dispostv.equals(ClientArduinoSignal.MOVIMIENTO_SIGNAL)){
                        status_eh.updateSensorMovimiento(numero,valor);
                        jLabel17.setText(Integer.toString(status_eh.getValorSensorMovimiento(
                                Integer.parseInt(ao.numero))));
                        
                        
                        
                    }else if(dispostv.equals(ClientArduinoSignal.INTERRUPTOR_LENGUETA_SIGNAL)){
                        status_eh.updateSensorMagnetico(numero,valor);
                        
                        switch(numero){
                            case 0: {
                                jLabel9.setText(Integer.toString(status_eh.getValorSensorMagnetico(
                                Integer.parseInt(ao.numero))));
                                break;
                            }
                            case 1: {
                                jLabel13.setText(Integer.toString(status_eh.getValorSensorMagnetico(
                                Integer.parseInt(ao.numero))));
                                break;
                            }
                            case 2: {
                                jLabel14.setText(Integer.toString(status_eh.getValorSensorMagnetico(
                                Integer.parseInt(ao.numero))));
                                break;
                            }
                            case 3: {
                                jLabel15.setText(Integer.toString(status_eh.getValorSensorMagnetico(
                                Integer.parseInt(ao.numero))));
                                break;
                            }

                        }
                    }
                }else if(object instanceof UsersOnline){
                    UsersOnline uo = (UsersOnline) object;
                    txt_usuarios.setText(Integer.toString(uo.users));
                }else if(object instanceof ServerMesage){
                    ServerMesage sm = (ServerMesage)object;
                    jTextField3.setText(sm.mensaje);
                }
                
            }
        });
    }
}
